import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Afious",
  description: "Generated by create next app",

  icons: {
    icon: "/images/favicon.png",
  }

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} gggf min-h-[100vh]`}>{children}</body>
    </html>
  );
}
